### ISSUE TITLE
unsafe-libyaml is also unmaintained

### ISSUE THREAD

**Issue by jayvdb** [cafkafk/serde-norway#17]
https://github.com/dtolnay/unsafe-libyaml will need to be replaced also.

There are not many active forks https://github.com/dtolnay/unsafe-libyaml/forks

or alternatives https://github.com/search?q=libyaml+language%3ARust&type=repositories&l=Rust&s=updated&o=desc

p.s. https://github.com/rustsec/advisory-db/issues/2132 mentions serde-norway

**Comment by cafkafk** [comment]
Thanks for making me aware, I will investigate as soon as I have time

**Comment by cafkafk** [comment]
I've decided that it's easier to just be my own upstream, working on this in https://github.com/cafkafk/unsafe-libyaml-norway/pull/1 (gonna be rough around the edges release engineering wise for a short bit as I figure out processes, I'll be more semver and less giant commits soon)
